### ISSUE TITLE
question about LDM_metadata.csv

### ISSUE THREAD

**Issue by wyhlovecpp** [RichardObi/ccnet#1]
Hi,

I have a question about how LDM_metadata.csv is constructed, and I see it's converted from [here](https://github.com/RichardObi/ccnet/blob/20ac912943d3b5636b4cc13ca01e03c701d2bf6d/src/python/preprocessing/ldm_metadata_processing.py#L11). But I don't know where the original file 'LDM_metadata.xlsx' is. I think it's duke dataset clinical_and_other_featuters.xlsx, but I don't seem to see the relevant code. If you can please answer this question for me.

**Comment by RichardObi** [comment]
Hi @wyhlovecpp, thank you for this question. As you pointed out, the 'LDM_metadata.csv' is derived [here](https://github.com/RichardObi/ccnet/blob/20ac912943d3b5636b4cc13ca01e03c701d2bf6d/src/python/preprocessing/ldm_metadata_processing.py#L11) from the file 'LDM_metadata.xlsx'. 'LDM_metadata.xlsx' is manually created from 'Clinical_and_Other_Features.xlsx', which is part of the Duke Dataset ([link](https://www.cancerimagingarchive.net/collection/duke-breast-cancer-mri/)).
I have now uploaded the 'LDM_metadata.xlsx' [here](https://github.com/RichardObi/ccnet/blob/main/data/LDM_metadata.xlsx). 
The reason LDM_metadata.xlsx was created was to identify which of the columns/attributes in Clinical_and_Other_Features.xlsx were relevant as context (i.e. conditional input) for the synthesis of the contrast-enhanced MRI images. In the LDM_metadata.xlsx there are 3 different potential contexts defined in columns R (short), S (medium), and T (long). In the final version of the [work](https://arxiv.org/abs/2403.13890) only the text defined in column R (DCE-Imaging info, without tumor characteristics info, without patient demographic info) was used. Hope this helps :)
